# .cnb.yml
$:
  vscode:
    - runner:
        cpus: 16
      services:
        - vscode
        - docker
      # 开发环境启动后会执行的任务
      stages:
        - name: tb
          script: npm config set registry https://registry.npmmirror.com
        - name: pnpm
          script: npm install -g pnpm 
        - name: install
          script: pnpm install
        - name: copy
          script: cp apps/dokploy/.env.example apps/dokploy/.env
canary:
  push:
    - runner:
        cpus: 64
    - services:
        - docker #声明后，流水线内可以直接使用docker命令
      env: 
        BETTER_AUTH_SECRET: "Kp8$rL2xQm5zTj9wSd3fGh7vBn6yUj2k"
      stages:
        - name: set docker tag
          script: echo -n "${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest"
          exports:
            info: IMAGE_TAG

        - name: docker build
          script: docker build -t $IMAGE_TAG .

        - name: push image
          script: docker push $IMAGE_TAG