# .cnb.yml
$:
  vscode:
    - docker:
        build: .cnb_dockerfile
        # 指定开发环境镜像，可以是任意可访问的镜像。
        # 如果 image 指定的镜像中已安装 code-server 代码服务，将使用单容器模式启动开发环境
        # 如果 image 指定的镜像中未安装 code-server 代码服务，将使用双容器模式启动开发环境
        # 如下镜像为 CNB 默认开发环境镜像，已安装代码服务，将使用单容器模式启动开发环境
        # 可按需替换为其他镜像
        #image: node:20.16.0
      services:
        - vscode
        - docker
      # 开发环境启动后会执行的任务
      stages:
        - name: tb
          script: npm config set registry https://registry.npmmirror.com
        - name: pnpm
          script: npm install -g pnpm
        - name: install
          script: pnpm install
        # - name: setup
        #   script: pnpm run dokploy:setup
        # - name: script
        #   script: pnpm run server:script