name: Docker Image CI

on:
  push:
    branches: [ "canary" ]
  pull_request:
    branches: [ "canary" ]

env:
  IMAGE_NAME: dokploy/dokploy

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      # 检出代码仓库
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 登录到私有Docker仓库
      - name: Login to CNB
        uses: docker/login-action@v3
        with:
          registry: docker.cnb.cool/ihuayu8/dokploy  # 私有仓库地址（如：registry.company.com）
          username: ${{ secrets.CNB_USERNAME }}  # 私有仓库用户名
          password: ${{ secrets.CNB_PASSWORD }}  # 私有仓库密码/令牌

      # 获取构建日期
      - name: Get build time
        id: get_time
        run: echo "BUILD_TIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      # 构建推送镜像
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            docker.cnb.cool/ihuayu8/dokploy:latest
            docker.cnb.cool/ihuayu8/dokploy:${{ steps.get_time.outputs.BUILD_TIME }}

      # 部署到远程服务器
      - name: Deploy to Remote Server via SSH
        uses: appleboy/ssh-action@master # 使用社区提供的 SSH Action
        with:
          host: ${{ secrets.REMOTE_HOST }} # 从 GitHub Secrets 读取远程服务器 IP 或主机名
          username: ${{ secrets.REMOTE_USER }} # 从 GitHub Secrets 读取远程服务器登录用户名
          password: ${{ secrets.REMOTE_PASSWORD }} # 从 GitHub Secrets 读取 SSH 私钥
          script: |
            echo "连接到远程服务器成功..."
            docker pull docker.cnb.cool/ihuayu8/dokploy:${{ steps.get_time.outputs.BUILD_TIME }}
            echo "镜像拉取成功..."
            docker service update --image docker.cnb.cool/ihuayu8/dokploy:${{ steps.get_time.outputs.BUILD_TIME }} dokploy
            echo "部署成功!"
